apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  selector:
      app: {{ .Values.web.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.web.servicePort }}
      targetPort: {{ .Values.web.container.port }}
  type: ClusterIP